language: csharp
mono: none
dotnet: 2.1.502
sudo: required
solution: AngularClientGenerator.sln
script:
 - cd src 
 - dotnet restore
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov AngularClientGenerator.Test
notifications:
  email: false