language: csharp
mono: none
dotnet: 2.1.502
script:
 - dotnet restore .\src\AngularClientGenerator.sln
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov .\src\AngularClientGenerator.Test
notifications:
  email: false